application:

  deployment:
    imagePullSecrets: null

    # Tilt live update only supports one replica
    replicas: 1

    image:
      repository: review
      tag: null

    volumes: null

    volumeMounts: null

    containerSecurityContext:
      readOnlyRootFilesystem: false

    readinessProbe:
      enabled: true
      failureThreshold: 50
      periodSeconds: 50
      successThreshold: 1
      timeoutSeconds: 50
      initialDelaySeconds: 50

    livenessProbe:
      enabled: true
      failureThreshold: 50
      periodSeconds: 50
      successThreshold: 1
      timeoutSeconds: 50
      initialDelaySeconds: 50

mongodb:

  readinessProbe:
    enabled: true
    failureThreshold: 50
    periodSeconds: 50
    successThreshold: 1
    timeoutSeconds: 50
    initialDelaySeconds: 50

  livenessProbe:
    enabled: true
    failureThreshold: 50
    periodSeconds: 50
    successThreshold: 1
    timeoutSeconds: 50
    initialDelaySeconds: 50
