application:
    
  deployment:
    imagePullSecrets: null

    # Tilt live update only supports one replica
    replicas: 1

    image:
      repository: review
      tag: null

mongodb:

  auth:
    enabled: true
    # So, that we don't need an ExternalSecret for local development
    rootPassword: password
    existingSecret: ""  