application:

  deployment:
    imagePullSecrets: null

    # Tilt live update only supports one replica
    replicas: 1

    image:
      repository: review
      tag: null

    volumes: null

    volumeMounts: null

    containerSecurityContext:
      readOnlyRootFilesystem: false
