apiVersion: v2
name: stakater-nordmart-review
description: A Helm chart for Kubernetes
dependencies:
- name: mongodb
  version: 10.0.5
  repository: "https://charts.bitnami.com/bitnami"
- name: application
  version: 0.1.*
  repository: https://stakater.github.io/stakater-charts  

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# DON'T TOUCH THIS
# This is the chart version. This version number is is incremented each time you make changes
# to the application.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.0
