##################################
# Application / App / Microservice
##################################
application: 

  applicationName: review

 # Deployment
  deployment:
    additionalLabels:
      appCategory: backend
    imagePullSecrets: nexus-docker-config-forked
    envFrom:
      review-config:
        type: configmap
        nameSuffix: config  
    image:
      repository: review
      tag: any-version
    resources: 
      limits:
        memory: 1Gi 
        cpu: 0.6
      requests:
        memory: 128Mi
        cpu: 0.1
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 60
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /actuator/health
          port: 8080
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 60
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /actuator/health
          port: 8080


  ## Prometheus Rule to trigger alerts based on ratings
  prometheusRule:
    enabled: true
    additionalLabels:
      prometheus: stakater-workload-monitoring
    groups:
      - name: nordmart-review-low-rating-warning
        rules:
          - alert: NordmartReviewLowRatingsCritical
            annotations:
              message: >-
                Total ratings below 2 has crossed the threshold 8. Total reviews: {{ $value }}.
            expr: >
              sum (nordmart_review_ratings_total{rating="2"} or nordmart_review_ratings_total{rating="1"}) > 8
            labels:
              severity: critical

  ## Alert manager Configuration to send the alerts
  alertmanagerConfig:
    enabled: true
    selectionLabels:
      alertmanagerConfig: workload
    spec:
      receivers:
        - name: nordmart-review-receiver
          slackConfigs:
            - apiURL:
                key: api_url
                name: nordmart-review-slack-webhook
              channel: nordmart-gabbar-application-alerts
              sendResolved: true
      route:
        groupBy:
          - alertname
          - severity
        groupInterval: 3m
        groupWait: 30s
        repeatInterval: 6h
        matchers:
          - name: alertname
            value: NordmartReviewLowRatingsCritical
        receiver: nordmart-review-receiver

  sealedSecret:
    enabled: true
    annotations:
      sealedsecrets.bitnami.com/cluster-wide: "true"
    files:
      - name: nordmart-review-slack-webhook
        encryptedData:
          api_url: AgCjZLtFmo2ZfwJf0AjAbM1qDsSEY1RFLL/0oqmVH7dX2E+O/n2ifIZmTUh+1pn/5a61caniNDbeTf6f2LVwRIvyvXMZBJzyJgUt+qzEVFhX5+3FcDMn9c1fWOcfj7AN3jEPtsp5wwqFADUBzoa4RBySLFQ37lh9nNd769LoK3Q9qSxQ96vSa1oAmKGQxo87FlZvwsXjKNT4w1OooDmWr7N3vdxZe/7jD8gNjSlmM6fYoXjIloVb5+Srrw2JjHy77zFhksZRVkR2GnH4fdCAQQs+1YFa4CTRZJqAkYVi6fkT8WBtqLU3oj/6jMuWjB4ooJGBkP5Ii26Jq4jUQOw4ytM3qdTk108IPa1RXt6HsSbuoVHiGhBB4JEaN4cFvQXmh7bPkt7+fb2KgQn/Fc0m6bmaMXFY/SjVhINVdCyzMuCljaLdfuwdA2qLbJV3Zi3/BVknNgCK76mTcalNIqIL4wb2tEbtITYYhN2kGTa7A7SBkBspptA5Mgi4cJAp+k+BMxHGDE6cHe55ZVluuyE/hGq+ELKdpjsu0BfmH2LfPtu1kvB+N5uytPqV+g0fsKf51nO2A+QL+MPnckdk6+sH5cQ+Isff7HBPKzJW1/dC+pjMgu8AXzYvG4zxBugZeabxmfgmEUIz1Bu1+pv5B7UTw67Xvyr8HuoRO3ItbMn7yynypxFYNntw5g1fHcHTym8MBSCOJKPvEU8Ehn6i8J+hGO+OZmIVIN6G3iBu9oGpH0BBYsbLUx1eZrfuyyaoBWUeJPlI4kP9PyjJOeHLBnGIgSSVtKwJtCQeT6DJWyIE/FEQ

  ## ConfigMap
  configMap:
    enabled: true
    files:
      config:
        DB_NAME: "nordmartDB"
        MONGO_HOST: "review-mongodb"

  ## RBAC
  rbac:
    serviceAccount:
      enabled: true
     
  ## Service     
  service:
    ports:
    - name: http
      port: 8080     
      targetPort: 8080

  ## Route
  route:
    enabled: true
    port:
      targetPort: http

  ## Service Monitor
  serviceMonitor:
    enabled: true

#####################
# MongoDB dependency
#####################
mongodb:

  fullnameOverride: review-mongodb  
  
  resources: 
     limits:
       memory: 1Gi 
       cpu: 0.5
     requests:
       memory: 128Mi
       cpu: 0.1
       
  auth:
    enabled: false

  podSecurityContext:
    enabled: false

  containerSecurityContext:
    enabled: false

#####################
# Grafana dashboard
#####################
grafanaDashboard:
  enabled: true
