##################################
# Application / App / Microservice
##################################
application: 

 applicationName: "review"

 deployment:
   additionalLabels:
     appCategory: "backend"
   imagePullSecrets: nexus-docker-config-forked
   envFrom:
    - type: configmap
      name: ""    
   image:
     repository: REPLACED_CI_PIPELINE
     tag: REPLACED_CI_PIPELINE
   resources: 
     limits:
       memory: 1Gi 
       cpu: 0.5
     requests:
       memory: 128Mi
       cpu: 0.1

   probes:
     readinessProbe:
       failureThreshold: 3
       periodSeconds: 60
       successThreshold: 1
       timeoutSeconds: 1
       initialDelaySeconds: 10
       httpGet:
         path: /actuator/health/readiness
         port: 8080
     livenessProbe:
       failureThreshold: 3
       periodSeconds: 60
       successThreshold: 1
       timeoutSeconds: 1
       initialDelaySeconds: 10
       httpGet:
         path: /actuator/health/readiness
         port: 8080

 configMap:
    enabled: true
    files:
    - nameSuffix: ""
      data:
        DB_NAME: "nordmartDB"
        MONGO_HOST: "review-mongodb"
        
 service:
   ports:
   - port: 8080
     name: https
     targetPort: 8080

 rbac:
   serviceAccount:
     enabled: true

 route:
    enabled: true
    port:
      targetPort: https

#####################
# MongoDB dependency
#####################
mongodb:

  fullnameOverride: review-mongodb  

  auth:
    enabled: false

  podSecurityContext:
    enabled: false

  containerSecurityContext:
    enabled: false
