##################################
# Application / App / Microservice
##################################
application: 

  applicationName: review

 # Deployment
  deployment:
    additionalLabels:
      appCategory: backend
    imagePullSecrets: nexus-docker-config-forked
    envFrom:
      review-config:
        type: configmap
        nameSuffix: config  
    image:
      repository: review
      tag: any-version
    resources: 
      limits:
        memory: 1Gi 
        cpu: 0.6
      requests:
        memory: 128Mi
        cpu: 0.1
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 60
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /actuator/health
          port: 8080
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 60
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /actuator/health
          port: 8080


  ## Prometheus Rule to trigger alerts based on ratings
  prometheusRule:
    enabled: true
    groups:
      - name: nordmart-review-low-rating-warning
        rules:
          - alert: NordmartReviewLowRatingsCritical
            annotations:
              message: >-
                Total ratings below 2 has crossed the threshold 8. Total reviews: {{ $value }}.
            expr: >
              sum (nordmart_review_ratings_total{rating="2"} or nordmart_review_ratings_total{rating="1"}) > 8
            for: 1m
            labels:
              severity: critical

 ## ConfigMap
  configMap:
    enabled: true
    files:
      config:
        DB_NAME: "nordmartDB"
        MONGO_HOST: "review-mongodb"

  ## RBAC
  rbac:
    serviceAccount:
      enabled: true
     
  ## Service     
  service:
    ports:
    - name: http
      port: 8080     
      targetPort: 8080

  ## Route
  route:
    enabled: true
    port:
      targetPort: http

  ## Service Monitor
  serviceMonitor:
    enabled: true

#####################
# MongoDB dependency
#####################
mongodb:

  fullnameOverride: review-mongodb  
  
  resources: 
     limits:
       memory: 1Gi 
       cpu: 0.5
     requests:
       memory: 128Mi
       cpu: 0.1
       
  auth:
    enabled: false

  podSecurityContext:
    enabled: false

  containerSecurityContext:
    enabled: false

#####################
# Grafana dashboard
#####################
grafanaDashboard:
  enabled: true