applicationName: "review"
deployment:
    annotations:
  podLabels:
    app: review
  volumes: {}
  image:
    repository: stakater/review
    tag: v0.0.1
  env:
  - name: DB_NAME
    value: "nordmartDB"
  - name: MONGO_HOST
    value: "mongodb-svc.default.svc.cluster.local"
  - name: JAEGER_ENDPOINT
    value: "http://jaeger-collector.istio-system:14268/api/traces"
  probes:
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /health
        port: 8080
    livenessProbe:
      failureThreshold: 3
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /health
        port: 8080
service:
  ports:
  - port: 8080
    name: https
    targetPort: 8080
rbac:
  create: true
  serviceAccount:
    create: true
configMap:
      enabled: false

ingress:
  enabled: false
  servicePort: 8080
  hosts:
    - chart-example.local
  annotations: 
    # kubernetes.io/ingress.class: external-ingress
    # ingress.kubernetes.io/rewrite-target: /
    # ingress.kubernetes.io/force-ssl-redirect: true
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
