applicationName: "review"
deployment:
  podLabels:
    app: review
  image:
    repository: docker.release.stakater.com:443/stakater/review
    tag: v0.0.2
  env:
  - name: DB_NAME
    value: "nordmartDB"
  - name: MONGO_HOST
    value: "mongodb-svc.nordmart-dev-apps.svc.cluster.local"
  - name: JAEGER_ENDPOINT
    value: "jaeger-collector.istio-system:14268/api/traces"
  imagePullSecrets: "docker-registry-nexus-secret"
rbac:
  create: false
  serviceAccount:
    name: default
configMap: {}
