---
# Source: application/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  labels:
    app: review
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-0.0.12"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: review
spec:
  selector:
    app: review
    
  ports:
    []
    
---
# Source: application/templates/deployment.yaml

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: review
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-0.0.12"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  annotations:
    reloader.stakater.com/auto: "true"
    
  name: review
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: review
        group: com.stakater.platform
        provider: stakater
        version: "1.0.0"
        chart: "application-0.0.12"
        release: "RELEASE-NAME"
        heritage: "Tiller"
        app: review
        
    spec:      
      imagePullSecrets:
      - name: docker-registry-nexus-secret
      containers:
      - name: review
        image: "docker.release.stakater.com:443/stakater/review:v0.0.2"
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_NAME
            value: nordmartDB
          - name: MONGO_HOST
            value: mongodb-svc.nordmart-dev-apps.svc.cluster.local
          - name: JAEGER_ENDPOINT
            value: http://jaeger-collector.istio-system:14268/api/traces
          
      serviceAccountName: default        
---
# Source: application/templates/clusterrole.yaml

---
# Source: application/templates/clusterrolebinding.yaml

---
# Source: application/templates/configmap.yaml

---
# Source: application/templates/ingress.yaml

---
# Source: application/templates/pvc.yaml

---
# Source: application/templates/role-binding.yaml

---
# Source: application/templates/role.yaml

---
# Source: application/templates/routes.yaml

---
# Source: application/templates/secret.yaml

---
# Source: application/templates/serviceaccount.yaml

