---
# Source: application/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  labels:
    app: review
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-0.0.13"
    release: "NAMESPACE_NAME-review"
    heritage: "Tiller"
  name: review
spec:
  selector:
    app: review
    
  ports:
    - name: https
      port: 8080
      targetPort: 8080
    